/**
 * Tests de la exclusión de vendorizado/generado/minificado en la ingesta (D5).
 *
 * La forma de estos tests sigue el requisito del frente, que tiene dos mitades
 * asimétricas y por eso hay MÁS casos negativos que positivos:
 *
 *   · Que la exclusión DISPARE es lo fácil: un `.pb.go` es un `.pb.go`.
 *   · Que NO se lleve puesto código legítimo del usuario es el requisito duro,
 *     porque un falso positivo saca código del análisis EN SILENCIO. Así que
 *     cada criterio tiene su caso de control pegado al lado, y hay uno
 *     (`prosa que habla de la convención`) que salió de un falso positivo
 *     medido de verdad: la primera versión de este módulo se excluía a SÍ
 *     MISMA porque su docstring nombra `DO NOT EDIT` en el medio de una
 *     oración.
 *
 * El último bloque es una compuerta sobre las fixtures REALES del proyecto:
 * ninguna de las 101 de `tests/fixtures/patterns` ni de las 133 de
 * `tests/fixtures/patterns-positive` puede quedar excluida. Si alguien afloja
 * un criterio de más, se entera acá y no seis olas después mirando por qué el
 * censo bajó.
 */
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { collectFiles } from "./code-analyzer.js";
import {
  classifyExclusion,
  classifyFile,
  dominantProvenance,
  excludedByContent,
  excludedByPath,
  excludedByProvenance,
  excludedByTestFilePattern,
  excludedDotnetTestProjectDir,
  excludedGherkinFeaturesDir,
  isFeaturesDirName,
  isTestDirName,
  type ExcludedFile,
} from "./ingest-exclusion.js";

const REPO_ROOT = path.resolve(import.meta.dirname, "..", "..", "..");

const created: string[] = [];

/** Escribe `files` (ruta relativa → contenido) bajo un tmpdir fresco. */
async function makeTree(files: Record<string, string>): Promise<string> {
  const root = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), "ck-ingest-excl-")));
  created.push(root);
  for (const [rel, contents] of Object.entries(files)) {
    const full = path.join(root, rel);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, contents);
  }
  return root;
}

afterEach(async () => {
  while (created.length > 0) {
    await fs.rm(created.pop()!, { recursive: true, force: true });
  }
});

/** Una línea sola, larga, como escupe un bundler: sin saltos y sin espacios. */
function minifiedLine(): string {
  const parts: string[] = [];
  for (let i = 0; i < 400; i++) parts.push(`function f${i}(a,b){return a+b*${i}}`);
  return `!function(e,t){${parts.join(";")}}(window,document);\n`;
}

describe("ingest-exclusion — nombre fijado por un generador", () => {
  it("excluye los sufijos que la herramienta escribe, no los que el proyecto elige", () => {
    const casos = [
      "api/service.pb.go",
      "api/service.pb.gw.go",
      "api/service_pb2.py",
      "api/service_pb2_grpc.py",
      "ui/Form.designer.cs",
      "ui/Window.g.cs",
      "ui/Window.g.i.cs",
      "ui/Model.generated.cs",
      "model/user.g.dart",
      "model/user.freezed.dart",
      "assets/jquery.min.js",
      "assets/vendor.min.mjs",
      "assets/closure-min.js",
    ];
    for (const rel of casos) {
      expect(excludedByPath(rel), rel).toMatchObject({ reason: "generated-name" });
    }
  });

  it("no excluye código del usuario cuyo nombre se PARECE al de un generador", () => {
    const casos = [
      // el sufijo tiene que ser el del generador, no una subcadena suelta
      "src/protobuf.go",
      "src/pb.go/handler.go",
      "src/pb2.py",
      "src/designer.cs",
      "src/generated.ts",
      "src/mining.js",
      "src/admin.js",
      // `.d.ts` está RECHAZADO a propósito: se escribe a mano tanto como se genera
      "types/express.d.ts",
      // fuente normal
      "src/user.go",
      "src/user.py",
      "src/User.cs",
    ];
    for (const rel of casos) {
      expect(excludedByPath(rel), rel).toBeNull();
    }
  });

  it("compara sin distinguir mayúsculas — `.Designer.cs` y `.designer.cs` son el mismo archivo", () => {
    expect(excludedByPath("ui/MainForm.Designer.cs")).toMatchObject({ reason: "generated-name" });
    expect(excludedByPath("assets/JQuery.Min.js")).toMatchObject({ reason: "generated-name" });
  });
});

describe("ingest-exclusion — marca de cabecera de código generado", () => {
  it("reconoce la marca de cada ecosistema que la publica", () => {
    const casos: Record<string, string> = {
      go: "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n",
      "go-stringer": "// Code generated by \"stringer -type=Pill\"; DO NOT EDIT.\n\npackage x\n",
      dotnet: "// <auto-generated />\nnamespace App { class C {} }\n",
      meta: "/* @generated */\nexport const T = 1;\n",
      "meta-bloque": "/**\n * @generated SignedSource<<abc>>\n */\nexport const T = 1;\n",
      protoc_py: "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\nclass A: pass\n",
      pelado: "// DO NOT EDIT\nexport const A = 1;\n",
      numeral: "# DO NOT EDIT: regenerar con `make api`\nclass A: pass\n",
      guion: "-- Automatically generated by schema-dump\nSELECT 1;\n",
      frase: "// This file was automatically generated by openapi-generator.\nexport const A = 1;\n",
      html: "<!-- Auto-generated by docgen -->\nexport const A = 1;\n",
    };
    for (const [nombre, texto] of Object.entries(casos)) {
      expect(excludedByContent(texto, false), nombre).toMatchObject({ reason: "generated-marker" });
    }
  });

  it("NO excluye prosa del usuario que MENCIONA la convención — el falso positivo medido", () => {
    // Éste es literalmente el caso que se llevó puesto a `ingest-exclusion.ts`
    // en la primera corrida de humo sobre `src/`: la marca aparece en el medio
    // de una oración, no arrancando una línea de cabecera.
    const prosa =
      "/**\n" +
      " * Detecta cabeceras de código generado. Donde hay un literal (`.pb.go`,\n" +
      " * `DO NOT EDIT`) es porque lo fija la herramienta, y también reconoce\n" +
      " * `@generated` de Meta.\n" +
      " */\nexport const X = 1;\n";
    expect(excludedByContent(prosa, false)).toBeNull();
  });

  it("NO excluye por advertencias escritas a mano que no declaran el archivo", () => {
    const casos: Record<string, string> = {
      "do not modify suelto": "// Do not modify this list without updating the parser.\nexport const A = 1;\n",
      "orden importa": "// The order below matters; do not edit it lightly when adding a case.\nexport const A = 1;\n",
      "generado en el medio": "export const A = 1;\n// el snapshot de abajo lo genera el script; do not edit\nexport const B = 2;\n",
    };
    for (const [nombre, texto] of Object.entries(casos)) {
      expect(excludedByContent(texto, false), nombre).toBeNull();
    }
  });

  it("la marca tiene que estar en la CABECERA: más abajo es una nota sobre un bloque", () => {
    const tarde = `${"export const A = 1;\n".repeat(60)}// Code generated by x. DO NOT EDIT.\n`;
    expect(excludedByContent(tarde, false)).toBeNull();
  });
});

describe("ingest-exclusion — minificado por forma", () => {
  it("excluye un bundle de una sola línea aunque el nombre no diga nada", () => {
    const veredicto = excludedByContent(minifiedLine(), false);
    expect(veredicto).toMatchObject({ reason: "minified-shape" });
    expect(veredicto!.detail).toMatch(/largo medio de línea/);
  });

  it("NO excluye código normal, ni siquiera con una línea larga aislada", () => {
    const normal = Array.from({ length: 200 }, (_, i) => `export const c${i} = ${i};`).join("\n");
    expect(excludedByContent(normal, false)).toBeNull();

    // Un blob embebido de 1500 caracteres sube el máximo pero no el promedio:
    // el criterio exige LAS DOS cosas justamente para no comerse este caso.
    const conBlob = `export const BLOB = "${"x".repeat(1500)}";\n${normal}`;
    expect(excludedByContent(conBlob, false)).toBeNull();
  });

  it("NO excluye un archivo de líneas largas pero sin ninguna línea de máquina", () => {
    // Promedio 150 (> 110) pero máximo 150 (< 1000): es Java con genéricos
    // largos, no salida de un minificador.
    const largo = Array.from({ length: 40 }, () => "x".repeat(150)).join("\n");
    expect(excludedByContent(largo, false)).toBeNull();
  });

  it("descarta la última línea cuando el texto viene cortado por el corte de lectura", () => {
    // Diez líneas normales y una undécima cortada a la mitad de algo enorme.
    // Sin el descarte, ese pedazo contaría como una línea de máquina.
    const cortado = `${"const a = 1;\n".repeat(10)}${"y".repeat(5000)}`;
    expect(excludedByContent(cortado, true)).toBeNull();
    // El mismo texto, si el archivo REALMENTE termina ahí, sí es una línea larga
    // de verdad… pero el promedio sigue mandando: 11 líneas, promedio ~460.
    expect(excludedByContent(cortado, false)).toMatchObject({ reason: "minified-shape" });
  });
});

describe("ingest-exclusion — classifyExclusion sobre archivos reales", () => {
  it("decide por nombre sin leer, y por contenido cuando el nombre no alcanza", async () => {
    const root = await makeTree({
      "api/service.pb.go": "package api\n",
      "api/kind.go": "// Code generated by stringer. DO NOT EDIT.\n\npackage api\n",
      "assets/app.a1b2c3.js": minifiedLine(),
      "src/main.go": 'package main\n\nfunc main() { println("hola") }\n',
    });
    const veredicto = async (rel: string) => classifyExclusion(path.join(root, rel), rel);

    expect(await veredicto("api/service.pb.go")).toMatchObject({ reason: "generated-name" });
    expect(await veredicto("api/kind.go")).toMatchObject({ reason: "generated-marker" });
    expect(await veredicto("assets/app.a1b2c3.js")).toMatchObject({ reason: "minified-shape" });
    expect(await veredicto("src/main.go")).toBeNull();
  });

  it("un archivo ilegible no se excluye por serlo — que falle el resto del pipeline", async () => {
    const root = await makeTree({ "src/main.go": "package main\n" });
    expect(await classifyExclusion(path.join(root, "no-existe.go"), "no-existe.go")).toBeNull();
  });
});

describe("collectFiles — la exclusión aplicada en la ingesta", () => {
  it("saca vendorizado, generado y minificado, y deja intacto el código del usuario", async () => {
    const root = await makeTree({
      // código del usuario, seis lenguajes
      "src/main.go": 'package main\n\nfunc main() { println("hola") }\n',
      "src/saludo.ts": "export function saludar(n: string) { return n; }\n",
      "src/caja.py": "class Caja:\n    def __init__(self, v):\n        self.v = v\n",
      "src/caja.rb": "class Caja\n  def initialize(v)\n    @v = v\n  end\nend\n",
      "src/Caja.cs": "namespace App { public class Caja { public int V; } }\n",
      "src/Caja.java": "package app;\npublic class Caja { public int v; }\n",
      // vendorizado por directorio (nombres agregados en D5)
      "third_party/upstream/leftpad.js": "export function leftPad(s) { return s; }\n",
      "deps/jason/lib/shim.js": "export const noop = () => {};\n",
      "obj/Debug/Temp.cs": "namespace App { class Temp {} }\n",
      "out/Build.java": "package app;\npublic class Build {}\n",
      // generado por nombre y por marca
      "api/service.pb.go": "package api\n\ntype Msg struct{ Id string }\n",
      "api/kind_string.go": "// Code generated by stringer. DO NOT EDIT.\n\npackage api\n",
      "api/Gen.cs": "// <auto-generated />\nnamespace App { class Gen {} }\n",
      // minificado por forma, con nombre inocente
      "assets/app.a1b2c3.js": minifiedLine(),
    });

    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });

    expect(quedaron.map((f) => f.path).sort()).toEqual([
      "src/Caja.cs",
      "src/Caja.java",
      "src/caja.py",
      "src/caja.rb",
      "src/main.go",
      "src/saludo.ts",
    ]);

    const porRuta = new Map(excluidos.map((e) => [e.path, e.reason]));
    expect(porRuta.get("api/service.pb.go")).toBe("generated-name");
    expect(porRuta.get("api/kind_string.go")).toBe("generated-marker");
    expect(porRuta.get("api/Gen.cs")).toBe("generated-marker");
    expect(porRuta.get("assets/app.a1b2c3.js")).toBe("minified-shape");
    // Los árboles se reportan por DIRECTORIO, no por archivo: adentro no se
    // entra, que es de dónde sale el ahorro.
    expect(porRuta.get("third_party")).toBe("dependency-tree");
    expect(porRuta.get("deps")).toBe("dependency-tree");
    expect(porRuta.get("obj")).toBe("dependency-tree");
    expect(porRuta.get("out")).toBe("dependency-tree");
  });

  it("sin el callback el resultado es el mismo — `onExcluded` no cambia qué entra", async () => {
    const root = await makeTree({
      "src/main.go": "package main\n",
      "api/service.pb.go": "package api\n",
    });
    const conCallback = await collectFiles(root, { onExcluded: () => {} });
    const sinCallback = await collectFiles(root);
    expect(sinCallback.map((f) => f.path)).toEqual(conCallback.map((f) => f.path));
    expect(sinCallback.map((f) => f.path)).toEqual(["src/main.go"]);
  });

  it("NO poda los directorios rechazados a propósito (`bin`, `packages`, `lib`)", async () => {
    // El motivo está escrito en `SKIP_DIRS`: son nombres que elige el
    // proyecto tanto como la herramienta, y podarlos saca fuente del usuario.
    const root = await makeTree({
      "bin/cli.js": "export function main() {}\n",
      "packages/core/src/index.ts": "export const x = 1;\n",
      "lib/helper.rb": "def helper; end\n",
    });
    const quedaron = await collectFiles(root);
    expect(quedaron.map((f) => f.path).sort()).toEqual([
      "bin/cli.js",
      "lib/helper.rb",
      "packages/core/src/index.ts",
    ]);
  });
});

describe("ingest-exclusion — árbol de test por nombre (D-TEST)", () => {
  it("reconoce los nombres de directorio que la herramienta busca por defecto, insensible a mayúsculas", () => {
    for (const name of ["spec", "test", "tests", "__tests__"]) {
      expect(isTestDirName(name), name).toBe(true);
      expect(isTestDirName(name.toUpperCase()), name.toUpperCase()).toBe(true);
    }
    // el caso medido: newtonsoft-json no tiene un directorio "tests" suelto,
    // pero SI un repo lo tuviera con otra grafía de mayúsculas debe agarrar igual
    expect(isTestDirName("Tests")).toBe(true);
    expect(isTestDirName("Test")).toBe(true);
  });

  it("`features` YA NO es un nombre que isTestDirName reconozca a secas — ver la sección 4b", () => {
    // El caso RECHAZADO de esta ola, medido: nest/guava/gitea tienen paquetes
    // de PRODUCCIÓN llamados `features`, sin Cucumber adentro. El nombre solo
    // ya no decide; ver `isFeaturesDirName`/`excludedGherkinFeaturesDir` abajo.
    expect(isTestDirName("features")).toBe(false);
    expect(isTestDirName("FEATURES")).toBe(false);
  });

  it("NO reconoce nombres de proyecto que sólo CONTIENEN la palabra test", () => {
    // El caso RECHAZADO por escrito: un fragmento de nombre de proyecto no es
    // el mismo criterio que el nombre EXACTO del directorio que la
    // herramienta busca.
    for (const name of ["Newtonsoft.Json.Tests", "guava-tests", "guava-testlib", "integration-tests", "testing"]) {
      expect(isTestDirName(name), name).toBe(false);
    }
  });

  it("reconoce los sufijos de archivo que la herramienta exige o busca por defecto", () => {
    const casos = [
      "orders_spec.rb",
      "orders_test.rb",
      "orders.test.js",
      "orders.spec.ts",
      "main_test.go",
      "test_orders.py",
      "orders_test.py",
    ];
    for (const rel of casos) {
      expect(excludedByTestFilePattern(rel), rel).toMatchObject({ reason: "test-tree" });
    }
  });

  it("NO excluye por sufijo Test/Tests suelto — el caso RECHAZADO, medido en guava", () => {
    // Los 10 archivos reales de guava-testlib que sobreviven hoy: código de
    // PRODUCCIÓN de una librería de soporte de test, no un test en sí mismo.
    const casos = [
      "MapInterfaceTest.java",
      "SortedMapInterfaceTest.java",
      "AbstractPackageSanityTests.java",
      "UnmodifiableCollectionTests.java",
      // C#: mismo argumento, ningún compilador distingue por este sufijo
      "TypeNameHandlingTests.cs",
      "JsonConvertTest.cs",
      // controles: nombres parecidos que no son el sufijo real
      "attest.go", // no es _test.go
      "testing.py", // no matchea test_*.py ni *_test.py
      "protest.rb", // no es _spec.rb ni _test.rb
    ];
    for (const rel of casos) {
      expect(excludedByTestFilePattern(rel), rel).toBeNull();
    }
  });
});

describe("ingest-exclusion — `features` sólo si tiene Gherkin adentro (D-TEST, sección 4b)", () => {
  it("isFeaturesDirName reconoce el nombre, insensible a mayúsculas, y nada más", () => {
    expect(isFeaturesDirName("features")).toBe(true);
    expect(isFeaturesDirName("FEATURES")).toBe(true);
    expect(isFeaturesDirName("Features")).toBe(true);
    expect(isFeaturesDirName("feature")).toBe(false);
    expect(isFeaturesDirName("my-features")).toBe(false);
  });

  it("excluye un directorio `features` con al menos un `.feature` directamente adentro — el caso real de jekyll", async () => {
    const root = await makeTree({
      "features/site_configuration.feature": "Feature: site configuration\n",
      "features/step_definitions.rb": "Given(/^x$/) { }\n",
      "features/support/helpers.rb": "module Helpers; end\n",
    });
    const veredicto = await excludedGherkinFeaturesDir(path.join(root, "features"));
    expect(veredicto).toMatchObject({ reason: "test-tree" });
    expect(veredicto!.detail).toMatch(/\.feature/);
  });

  it("NO excluye un `features` sin ningún `.feature` adentro — el caso medido: nest/guava/gitea", async () => {
    // El caso RECHAZADO por esta ola, con los tres ejemplos reales del
    // corpus: una interfaz de TypeScript, una librería de soporte de test de
    // Java, un módulo de frontend — ninguno es Cucumber, ninguno tiene un
    // `.feature`.
    const root = await makeTree({
      "packages/common/interfaces/features/execution-context.interface.ts":
        "export interface ExecutionContext {}\n",
      "guava-testlib/collect/testing/features/CollectionSize.java":
        "package com.google.common.collect.testing.features;\npublic enum CollectionSize {}\n",
      "web_src/js/features/notification.ts": "export function setup() {}\n",
    });
    for (const dir of [
      "packages/common/interfaces/features",
      "guava-testlib/collect/testing/features",
      "web_src/js/features",
    ]) {
      expect(await excludedGherkinFeaturesDir(path.join(root, dir)), dir).toBeNull();
    }
  });

  it("un `.feature` en un SUBDIRECTORIO de `features` no cuenta — sólo el nivel inmediato", async () => {
    // Documenta la elección de costo (sección 4b): el chequeo no recorre,
    // sólo mira el nivel de arriba. Un `.feature` más abajo no excluye nada
    // acá — que decida el walk normal, que si entra va a leer ese archivo
    // como cualquier otro (y `.feature` no tiene extensión reconocida, así
    // que tampoco se analiza como fuente).
    const root = await makeTree({
      "features/nested/deep.feature": "Feature: nested\n",
      "features/module.ts": "export const x = 1;\n",
    });
    expect(await excludedGherkinFeaturesDir(path.join(root, "features"))).toBeNull();
  });

  it("un directorio inexistente no excluye — que falle el resto del pipeline", async () => {
    const root = await makeTree({ "src/main.ts": "export const x = 1;\n" });
    expect(await excludedGherkinFeaturesDir(path.join(root, "no-existe"))).toBeNull();
  });
});

describe("ingest-exclusion — proyecto .NET que el SDK trata como test (D-TEST)", () => {
  it("excluye el directorio cuando el .csproj referencia Microsoft.NET.Test.Sdk", async () => {
    const root = await makeTree({
      "Foo.Tests/Foo.Tests.csproj":
        '<Project Sdk="Microsoft.NET.Sdk">\n  <ItemGroup>\n    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />\n    <PackageReference Include="NUnit" Version="3.13.0" />\n  </ItemGroup>\n</Project>\n',
      "Foo.Tests/SomeTest.cs": "namespace Foo.Tests { public class SomeTest {} }\n",
    });
    const veredicto = await excludedDotnetTestProjectDir(path.join(root, "Foo.Tests"), [
      "Foo.Tests.csproj",
      "SomeTest.cs",
    ]);
    expect(veredicto).toMatchObject({ reason: "test-tree" });
    expect(veredicto!.detail).toMatch(/Microsoft\.NET\.Test\.Sdk/);
  });

  it("NO excluye un proyecto .NET normal, aunque el NOMBRE diga Test(s) — el caso medido en newtonsoft-json", async () => {
    // Newtonsoft.Json.FuzzTests y Newtonsoft.Json.TestConsole: los dos con
    // "Test(s)" en el nombre, ninguno referencia el SDK de test, ninguno se excluye.
    const root = await makeTree({
      "Foo.FuzzTests/Foo.FuzzTests.csproj":
        '<Project Sdk="Microsoft.NET.Sdk">\n  <ItemGroup>\n    <ProjectReference Include="..\\Foo\\Foo.csproj" />\n  </ItemGroup>\n</Project>\n',
      "Foo.TestConsole/Foo.TestConsole.csproj":
        '<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>\n</Project>\n',
    });
    expect(
      await excludedDotnetTestProjectDir(path.join(root, "Foo.FuzzTests"), ["Foo.FuzzTests.csproj"]),
    ).toBeNull();
    expect(
      await excludedDotnetTestProjectDir(path.join(root, "Foo.TestConsole"), ["Foo.TestConsole.csproj"]),
    ).toBeNull();
  });

  it("sin descriptor de proyecto no hay nada que decidir", async () => {
    const root = await makeTree({ "src/main.cs": "namespace App {}\n" });
    expect(await excludedDotnetTestProjectDir(path.join(root, "src"), ["main.cs"])).toBeNull();
  });

  it("un .csproj ilegible no excluye el directorio — que falle el resto del pipeline", async () => {
    const root = await makeTree({ "src/placeholder.cs": "namespace App {}\n" });
    expect(
      await excludedDotnetTestProjectDir(path.join(root, "src"), ["NoExiste.csproj"]),
    ).toBeNull();
  });
});

describe("collectFiles — árbol de test aplicado en la ingesta (D-TEST)", () => {
  it("poda un proyecto .NET completo por su .csproj, y reporta el DIRECTORIO, no cada archivo", async () => {
    const root = await makeTree({
      "Src/Newtonsoft.Json/Core.cs": "namespace Newtonsoft.Json { public class Core {} }\n",
      "Src/Newtonsoft.Json.Tests/Newtonsoft.Json.Tests.csproj":
        '<Project Sdk="Microsoft.NET.Sdk">\n  <ItemGroup>\n    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />\n  </ItemGroup>\n</Project>\n',
      "Src/Newtonsoft.Json.Tests/TypeNameHandlingTests.cs":
        "namespace Newtonsoft.Json.Tests { public class TypeNameHandlingTests {} }\n",
      "Src/Newtonsoft.Json.Tests/TestObjects/Subclass.cs":
        "namespace Newtonsoft.Json.Tests.TestObjects { public class Subclass {} }\n",
    });
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });

    expect(quedaron.map((f) => f.path)).toEqual(["Src/Newtonsoft.Json/Core.cs"]);
    // UNA sola exclusión, del directorio del proyecto — no una por archivo
    // adentro (`TypeNameHandlingTests.cs` y `TestObjects/Subclass.cs` nunca
    // se visitan, igual que `dependency-tree`).
    expect(excluidos).toHaveLength(1);
    expect(excluidos[0]).toMatchObject({
      path: "Src/Newtonsoft.Json.Tests",
      reason: "test-tree",
    });
  });

  it("poda un directorio de test por nombre insensible a mayúsculas — el bug de D-TEST", () => {
    // Regresión: antes de D-TEST, `TEST_DIR_NAMES.has(entry.name)` comparaba
    // sin normalizar mayúsculas, así que un `Test/`/`Tests/` (grafía común en
    // repos .NET en Windows) NO se podaba.
    expect(isTestDirName("Test")).toBe(true);
    expect(isTestDirName("TESTS")).toBe(true);
  });

  it("poda un directorio 'Tests' con mayúscula dentro del árbol real, y lo reporta", async () => {
    const root = await makeTree({
      "src/main.go": "package main\n\nfunc main() {}\n",
      "Tests/regression.go": "package tests\n\nfunc Helper() {}\n",
    });
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });
    expect(quedaron.map((f) => f.path)).toEqual(["src/main.go"]);
    expect(excluidos).toContainEqual(
      expect.objectContaining({ path: "Tests", reason: "test-tree" }),
    );
  });

  it("sigue podando spec/test/tests/__tests__ por nombre, y ahora lo REPORTA (antes era silencioso)", async () => {
    const root = await makeTree({
      "src/orders.rb": "class Orders\nend\n",
      "spec/orders_spec.rb": "describe('Orders') {}\n",
    });
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });
    expect(quedaron.map((f) => f.path)).toEqual(["src/orders.rb"]);
    expect(excluidos).toContainEqual(expect.objectContaining({ path: "spec", reason: "test-tree" }));
  });

  it("`features` en el árbol real: poda si tiene Gherkin, camina normal si no — el bug de esta ola", async () => {
    const root = await makeTree({
      // Árbol Cucumber real, forma jekyll: se poda entero.
      "features/site.feature": "Feature: site\n",
      "features/step_definitions.rb": "Given(/^x$/) { }\n",
      // Paquete de producción con el mismo nombre, forma nest: se camina normal.
      "packages/common/interfaces/features/execution-context.interface.ts":
        "export interface ExecutionContext {}\n",
    });
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });
    expect(quedaron.map((f) => f.path)).toEqual([
      "packages/common/interfaces/features/execution-context.interface.ts",
    ]);
    expect(excluidos).toContainEqual(expect.objectContaining({ path: "features", reason: "test-tree" }));
    expect(excluidos.some((e) => e.path.startsWith("packages/"))).toBe(false);
  });
});

describe("compuerta de seguridad — las fixtures del proyecto no pierden ni un archivo", () => {
  it("tests/fixtures/patterns: cero exclusiones", async () => {
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(path.join(REPO_ROOT, "tests", "fixtures", "patterns"), {
      onExcluded: (e) => excluidos.push(e),
    });
    expect(excluidos.map((e) => `${e.path} [${e.reason}] ${e.detail}`)).toEqual([]);
    expect(quedaron.length).toBe(101);
  });

  it("tests/fixtures/patterns-positive: cero exclusiones", async () => {
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(path.join(REPO_ROOT, "tests", "fixtures", "patterns-positive"), {
      onExcluded: (e) => excluidos.push(e),
    });
    expect(excluidos.map((e) => `${e.path} [${e.reason}] ${e.detail}`)).toEqual([]);
    expect(quedaron.length).toBe(133);
  });

  it("el código de PRODUCCIÓN del propio analizador no se excluye a sí mismo", async () => {
    // Regresión directa del falso positivo medido: `src/server/services/`
    // documenta las marcas que detecta, así que es el peor caso disponible
    // para el criterio de cabecera (D5) y de árbol de test (D-TEST): este
    // mismo archivo nombra `.test.ts`, `DO NOT EDIT`, etc. en prosa.
    //
    // D-TEST auditó un exclusión que YA EXISTÍA en silencio: antes de esta
    // ola, `code-analyzer.ts` descartaba cada `*.test.ts` con un `continue`
    // que nunca llamaba a `onExcluded` — el archivo NO se analizaba (esto no
    // cambió: `*.test.ts` es exactamente el patrón de Jest/Vitest, ya vivía
    // en `TEST_FILE_PATTERNS` antes de D-TEST), pero la exclusión era invisible
    // para esta misma compuerta de seguridad. D-TEST la hizo auditable; la
    // compuerta ahora exige explícitamente que sea SÓLO eso lo que aparece —
    // ningún `generated-name`/`generated-marker`/`minified-shape`/
    // `dependency-tree` sobre código de producción real.
    const excluidos: ExcludedFile[] = [];
    await collectFiles(path.join(REPO_ROOT, "src"), { onExcluded: (e) => excluidos.push(e) });

    const noTest = excluidos.filter((e) => e.reason !== "test-tree");
    expect(noTest.map((e) => `${e.path} [${e.reason}] ${e.detail}`)).toEqual([]);

    // Lo único que puede aparecer es el propio suite de tests del analizador
    // (`*.test.ts`), y nada más — ni un `.ts` de producción confundido con test.
    for (const e of excluidos) {
      expect(e.reason).toBe("test-tree");
      expect(path.basename(e.path)).toMatch(/\.test\.ts$/);
    }
    expect(excluidos.length).toBeGreaterThan(0); // el propio suite existe: la compuerta no pasa por vacuidad
  });
});

/**
 * P11 — la sexta categoría: PROCEDENCIA AJENA, cableada en la ingesta.
 *
 * Todas las cabeceras de acá abajo son texto REAL del corpus, copiado verbatim
 * y con su ruta al lado, por la misma razón que las de
 * `detect/primitivas/n10-no-es-producto.test.ts`: una heurística sobre texto
 * encuentra sus bugs contra el texto que existe, no contra el que uno
 * escribiría para demostrar que funciona.
 */
const CABECERA_PROPIA = // corpus/hugo/tpl/tplimpl/template.go (y otros 400)
  "// Copyright 2024 The Hugo Authors. All rights reserved.\n" +
  "//\n" +
  "// Licensed under the Apache License, Version 2.0 (the \"License\");\n";
const CABECERA_AJENA = // corpus/hugo/tpl/internal/go_templates/texttemplate/exec.go
  "// Copyright 2011 The Go Authors. All rights reserved.\n" +
  "// Use of this source code is governed by a BSD-style\n" +
  "// license that can be found in the LICENSE file.\n";

/** `n` archivos Go bajo `dir`, todos con la misma cabecera. */
function conCabecera(dir: string, n: number, header: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (let i = 0; i < n; i++) {
    files[`${dir}/f${i}.go`] = `${header}\npackage p\n\nfunc F${i}() {}\n`;
  }
  return files;
}

describe("collectFiles — procedencia ajena aplicada en la ingesta (N10/P11)", () => {
  it("saca el archivo cuya cabecera atribuye la autoría a otro, y lo reporta como `vendored-provenance`", async () => {
    const root = await makeTree({
      ...conCabecera("src", 60, CABECERA_PROPIA),
      "src/sin-cabecera.go": "package p\n\nfunc G() {}\n",
      "tpl/internal/copiado/exec.go": `${CABECERA_AJENA}\npackage template\n\nfunc Exec() {}\n`,
    });

    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });

    expect(excluidos.map((e) => e.path)).toEqual(["tpl/internal/copiado/exec.go"]);
    expect(excluidos[0]!.reason).toBe("vendored-provenance");
    // El detalle tiene que dejar auditar la decisión sin releer nada: las DOS
    // atribuciones, la del archivo y la del repo.
    // La firma es el conjunto de palabras ORDENADO (dos escrituras del mismo
    // autor tienen que dar la misma clave), así que "The Go Authors" canoniza
    // a "authors go" — sin `the`, que es muletilla.
    expect(excluidos[0]!.detail).toContain("authors go");
    expect(excluidos[0]!.detail).toContain("authors hugo");
    // El que no declara nada NO es ajeno: la ausencia de evidencia no es evidencia.
    expect(quedaron.map((f) => f.path)).toContain("src/sin-cabecera.go");
    expect(quedaron).toHaveLength(61);
  });

  it("LA POBLACIÓN es la de los archivos ANALIZADOS: lo podado no vota qué es la convención del repo", async () => {
    // El caso que obliga a que la fase 2 se arme con las firmas que juntó el
    // recorrido y no con un segundo barrido del disco: acá hay MÁS archivos con
    // la cabecera ajena que con la propia, pero todos los ajenos viven en
    // árboles que la ingesta ya podó (dependencias y test). Si votaran, la
    // firma dominante se caería por falta de mayoría y el archivo copiado se
    // quedaría adentro.
    const root = await makeTree({
      ...conCabecera("src", 60, CABECERA_PROPIA),
      ...conCabecera("vendor/upstream", 100, CABECERA_AJENA),
      ...conCabecera("test", 100, CABECERA_AJENA),
      "tpl/internal/copiado/exec.go": `${CABECERA_AJENA}\npackage template\n\nfunc Exec() {}\n`,
    });

    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });

    expect(quedaron).toHaveLength(60);
    expect(excluidos.filter((e) => e.reason === "vendored-provenance").map((e) => e.path)).toEqual([
      "tpl/internal/copiado/exec.go",
    ]);
  });

  it("bajo el piso de muestra no se toca NADA — el modo de falla es no excluir", async () => {
    // 49 archivos firmados en total (48 propios + el copiado, que también
    // cuenta como muestra): uno menos que `MIN_FIRMADOS`. La convención del
    // repo no está probada, así que el copiado se queda adentro. Es la
    // diferencia entre "no es del repo" y "no sé qué es este repo".
    const root = await makeTree({
      ...conCabecera("src", 48, CABECERA_PROPIA),
      "tpl/internal/copiado/exec.go": `${CABECERA_AJENA}\npackage template\n\nfunc Exec() {}\n`,
    });
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });
    expect(excluidos).toEqual([]);
    expect(quedaron).toHaveLength(49);
    // Y con UN archivo firmado más, el mismo árbol sí lo saca: la compuerta es
    // el tamaño de la muestra, no el archivo.
    const root2 = await makeTree({
      ...conCabecera("src", 49, CABECERA_PROPIA),
      "tpl/internal/copiado/exec.go": `${CABECERA_AJENA}\npackage template\n\nfunc Exec() {}\n`,
    });
    const excluidos2: ExcludedFile[] = [];
    await collectFiles(root2, { onExcluded: (e) => excluidos2.push(e) });
    expect(excluidos2.map((e) => e.path)).toEqual(["tpl/internal/copiado/exec.go"]);
  });

  it("un repo que no usa cabeceras no pierde ni un archivo", async () => {
    const root = await makeTree({
      ...conCabecera("src", 60, ""),
      "tpl/internal/copiado/exec.go": `${CABECERA_AJENA}\npackage template\n\nfunc Exec() {}\n`,
    });
    const excluidos: ExcludedFile[] = [];
    const quedaron = await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });
    expect(excluidos).toEqual([]);
    expect(quedaron).toHaveLength(61);
  });

  it("dos escrituras de la MISMA atribución no se marcan (comparación por subconjunto)", async () => {
    // `corpus/hugo` tiene las dos grafías conviviendo; si la comparación fuera
    // por igualdad exacta, la minoritaria se marcaría como ajena — 400 falsos
    // positivos de un saque.
    const root = await makeTree({
      ...conCabecera("src", 60, CABECERA_PROPIA),
      "common/loggers/logger.go":
        "// Copyright 2024 The Hugo Authors and contributors. All rights reserved.\n\npackage p\n\nfunc H() {}\n",
    });
    const excluidos: ExcludedFile[] = [];
    await collectFiles(root, { onExcluded: (e) => excluidos.push(e) });
    expect(excluidos).toEqual([]);
  });

  it("`classifyFile` saca la firma del MISMO texto que ya leyó, y no la saca de un archivo excluido", async () => {
    const root = await makeTree({
      "src/propio.go": `${CABECERA_PROPIA}\npackage p\n`,
      "src/anonimo.go": "package p\n",
      "src/kind_string.go": `// Code generated by stringer. DO NOT EDIT.\n${CABECERA_AJENA}\npackage p\n`,
    });
    const propio = await classifyFile(path.join(root, "src/propio.go"), "src/propio.go");
    expect(propio).toEqual({ exclusion: null, provenance: "authors hugo" });
    expect(await classifyFile(path.join(root, "src/anonimo.go"), "src/anonimo.go")).toEqual({
      exclusion: null,
      provenance: null,
    });
    // Un archivo que ya no entra al análisis tampoco vota.
    const generado = await classifyFile(path.join(root, "src/kind_string.go"), "src/kind_string.go");
    expect(generado.exclusion).toMatchObject({ reason: "generated-marker" });
    expect(generado.provenance).toBeNull();
  });

  it("`dominantProvenance`/`excludedByProvenance` son las dos mitades de la fase 2", async () => {
    const firmas = [...Array(60).fill("authors hugo"), "go authors", null];
    const dominante = dominantProvenance(firmas);
    expect(dominante).toBe("authors hugo");
    expect(excludedByProvenance("go authors", dominante)).toMatchObject({
      reason: "vendored-provenance",
    });
    expect(excludedByProvenance("authors hugo", dominante)).toBeNull();
    expect(excludedByProvenance(null, dominante)).toBeNull();
    // Sin dominante no hay contra qué comparar: nadie es ajeno.
    expect(dominantProvenance(["go authors", null])).toBeNull();
    expect(excludedByProvenance("go authors", null)).toBeNull();
  });
});
