/**
 * Exclusión de código vendorizado, generado, minificado y de ÁRBOL DE TEST —
 * D5 del registro (vendorizado/generado/minificado, implementado con efecto
 * medido cero por falta de corpus) más D-TEST (árbol de test, esta ola, con
 * corpus y con efecto medido).
 *
 * QUÉ PROBLEMA RESUELVE, LAS DOS MITADES. El analizador trata todo archivo con
 * una extensión conocida como código del usuario. No siempre lo es:
 *   · Un `.js` minificado de 200 KB en una sola línea, un `.pb.go` escupido
 *     por protoc y un árbol `third_party/` copiado de upstream (D5) producen
 *     hallazgos que nadie puede accionar (no se edita código generado: se
 *     regenera) y envenenan las métricas agregadas y las consultas de grafo.
 *   · Un archivo de test (D-TEST) no es generado ni vendorizado — lo escribió
 *     una persona — pero repite a propósito la misma forma cientos de veces
 *     (un `describe`/`it`/`[Fact]` por caso) y eso hace que la duplicación
 *     estructural y las hipótesis de patrón que cuelgan de ella (Composite,
 *     Facade, Template Method…) traten el árbol de test como si fuera una
 *     jerarquía de dominio o una fachada de producción que alguien puentea.
 *     Medido sobre el corpus de 8 lenguajes: el 52 % de las hipótesis vivas de
 *     newtonsoft-json colgaban de `Newtonsoft.Json.Tests/` antes de esta ola —
 *     ver la sección 4-5 más abajo para el mecanismo y el número después.
 *
 * LA REGLA QUE GOBIERNA ESTE ARCHIVO — y la razón de que casi todo comentario
 * de acá abajo sea una justificación y no una descripción: **está prohibido
 * resolver esto con una lista de nombres de proyecto o de librería**. Nada de
 * `jquery.min.js`, nada de "los dos archivos de jekyll", nada de "el árbol se
 * llama `Newtonsoft.Json.Tests`". Cada criterio de acá tiene que ser una
 * propiedad ESTRUCTURAL del formato — algo que sea verdad porque una
 * herramienta escribió el archivo o porque otra herramienta lo BUSCA con ese
 * criterio por defecto, no porque el repo se llame como se llama. Donde hay un
 * literal (`.pb.go`, `DO NOT EDIT`, `Microsoft.NET.Test.Sdk`) es porque ese
 * literal lo FIJA o lo EXIGE la herramienta, no el proyecto que lo consume, y
 * eso queda escrito entrada por entrada, con su RECHAZADO al lado cuando la
 * tentación de admitir un nombre parecido pero no fijado por ninguna
 * herramienta ya se evaluó y se descartó. Un criterio que no se pueda
 * justificar así no entra.
 *
 * REQUISITO DE SEGURIDAD, más fuerte que el de cobertura: excluir código
 * legítimo del usuario es un bug; dejar pasar un archivo vendorizado o de test
 * es ruido. Ante la duda, NO se excluye. Por eso hay entradas explícitamente
 * RECHAZADAS con el motivo escrito (`bin`, `packages`, `lib` en `SKIP_DIRS`;
 * `do not modify` y `generated by` a secas y `Test(s).ext` suelto acá abajo):
 * son las que un criterio "razonable" pero laxo se llevaría puestas.
 *
 * POR QUÉ ALGUNOS CRITERIOS NO VIVEN ACÁ. Las categorías 1-3 (D5) y 5
 * (D-TEST, proyecto .NET) son POR ARCHIVO O POR DESCRIPTOR: hay que ver el
 * nombre o el contenido de cada uno. Las categorías "árbol de dependencias" y
 * "directorio de test por nombre" (`spec`, `test`, `tests`, `__tests__`, y
 * `features` con su chequeo estructural aparte — sección 4b) son por
 * DIRECTORIO, y su valor está en no visitar el árbol: podar cuesta una
 * comparación, clasificar archivo por archivo cuesta exactamente lo que se
 * quería evitar. Por eso esas dos podan en el walk de `collectFiles`
 * (`SKIP_DIRS` para dependencias; `isTestDirName`/`isFeaturesDirName` de este
 * módulo para test, invocado desde `code-analyzer.ts`) y no hacen la poda
 * ellas mismas acá — pero el PREDICADO de test-por-nombre sí vive acá (
 * `isTestDirName`/`isFeaturesDirName`/`excludedGherkinFeaturesDir`/
 * `excludedByTestFilePattern`), junto a sus hermanos, para que un solo
 * archivo declare y justifique las seis categorías. La sexta (procedencia
 * ajena, N10/P11) es la única que NO se contesta mirando un solo archivo
 * —compara contra un estadístico del repo entero— y por eso la ingesta la
 * resuelve en dos fases sin leer nada de más; ver la sección 6. El tipo
 * {@link ExclusionReason} nombra las dos igual, porque el recorrido reporta
 * las podas para que la medición del frente pueda contarlas.
 *
 * DÓNDE SE APLICA. En la ingesta (`collectFiles` de `code-analyzer.ts`), que
 * es el único punto por el que un archivo entra al análisis. Excluir acá
 * significa que el archivo no produce `FileFacts`, no aporta nodos ni aristas
 * al grafo y no cuenta en el censo — no que se filtre después.
 */
import fs from "node:fs/promises";
import path from "node:path";

import {
  esProcedenciaAjena,
  firmaDeProcedencia,
  procedenciaDominante,
} from "./detect/primitivas/n10-no-es-producto.js";

/** Por qué se excluyó un archivo (o, para `dependency-tree`, un directorio). */
export type ExclusionReason =
  /**
   * Un árbol que una herramienta de paquetes/build escribe y posee. Lo decide
   * el walk podando el directorio entero — ver el docstring del módulo.
   */
  | "dependency-tree"
  /** El NOMBRE lo fija un generador de código (sufijo obligatorio de la herramienta). */
  | "generated-name"
  /** El CONTENIDO se declara generado en su cabecera (marca convencional). */
  | "generated-marker"
  /** La FORMA del texto es de salida de un minificador, no de código escrito a mano. */
  | "minified-shape"
  /**
   * D-TEST — árbol o archivo de test, por una de dos vías, las dos con
   * criterio de admisión escrito: (a) el nombre de DIRECTORIO/archivo que la
   * propia herramienta de test busca por defecto o exige para descubrir el
   * archivo (Maven/Gradle, RSpec, Minitest, pytest, Jest/Vitest, el compilador
   * de Go), podado por directorio igual que `dependency-tree` cuando aplica; o
   * (b) —el hueco que este módulo no cubría— un DESCRIPTOR DE PROYECTO .NET
   * (`.csproj`/`.fsproj`/`.vbproj`) que referencia `Microsoft.NET.Test.Sdk`, el
   * paquete que `dotnet test`/VSTest exige para reconocer el proyecto como
   * ejecutable-de-test, sea cual sea el framework de aserciones que use por
   * encima. Ver la sección 4 y 5 del archivo.
   */
  | "test-tree"
  /**
   * N10/P11 — el archivo declara en su propia CABECERA una atribución de
   * autoría distinta de la que declara la abrumadora mayoría de los archivos
   * del mismo repo: una copia traída de afuera y pegada adentro. Es la
   * categoría que el docstring de este módulo declara desde D5 ("un árbol
   * `third_party/` copiado de upstream") y que hasta esta ola sólo se cubría
   * cuando el copista había tenido la gentileza de ponerle a la carpeta uno de
   * los nombres de `SKIP_DIRS` — es decir, casi nunca: la copia de
   * `text/template`+`html/template` de la stdlib de Go que hugo tiene adentro
   * vive en `tpl/internal/go_templates/`, y son 31 de los 34 archivos que el
   * criterio saca de ese repo. Ver la sección 6.
   */
  | "vendored-provenance";

export interface Exclusion {
  reason: ExclusionReason;
  /** Qué se observó, concreto, para poder auditar una exclusión sin releer el archivo. */
  detail: string;
}

export interface ExcludedFile extends Exclusion {
  /**
   * Ruta relativa al repo. Es un archivo salvo cuando `reason` es
   * `dependency-tree`, donde es el directorio podado (los archivos de adentro
   * nunca se visitan, así que no hay nada más específico que reportar).
   */
  path: string;
}

/* ── 1. Nombres que fija un generador ─────────────────────────────────────
 *
 * Sufijos que NO son convención social sino parte del contrato de la
 * herramienta: el generador escribe exactamente ese nombre y el compilador o
 * el runtime lo espera. Por eso son genéricos: valen en cualquier repo que
 * use esa herramienta, y no valen en ningún otro lado.
 *
 * Se comparan sobre el basename en minúsculas (`.Designer.cs` y
 * `.designer.cs` son el mismo archivo en Windows, y ambos aparecen en repos
 * reales).
 *
 * RECHAZADO: `.d.ts`. Es salida de `tsc` la mayoría de las veces, pero
 * también se escribe a mano para tipar una dependencia sin tipos, y no hay
 * forma de distinguirlo por el nombre. Requisito de seguridad: no entra.
 */
const GENERATED_NAME_SUFFIXES: readonly { suffix: string; tool: string }[] = [
  // protoc + protoc-gen-go: el nombre de salida es `<proto>.pb.go`, fijo.
  { suffix: ".pb.go", tool: "protoc-gen-go" },
  // grpc-gateway, misma familia.
  { suffix: ".pb.gw.go", tool: "protoc-gen-grpc-gateway" },
  // protoc para Python: `<proto>_pb2.py` y `<proto>_pb2_grpc.py`, fijos.
  { suffix: "_pb2.py", tool: "protoc (python_out)" },
  { suffix: "_pb2_grpc.py", tool: "grpc_tools.protoc" },
  // build_runner de Dart escribe `<fuente>.g.dart` / `<fuente>.freezed.dart`.
  // Todavía no hay gramática Dart cargada, así que hoy esto no puede excluir
  // nada: entra igual porque el criterio es del formato, no del corpus.
  { suffix: ".g.dart", tool: "dart build_runner" },
  { suffix: ".freezed.dart", tool: "dart freezed" },
  // Diseñadores de Visual Studio (WinForms/resx) y compilador XAML: el
  // parcial generado es `<tipo>.designer.cs` / `<tipo>.g.cs` / `.g.i.cs`.
  { suffix: ".designer.cs", tool: "Visual Studio designer" },
  { suffix: ".g.cs", tool: "compilador XAML / source generator de Roslyn" },
  { suffix: ".g.i.cs", tool: "compilador XAML" },
  { suffix: ".generated.cs", tool: "generador de código .NET" },
  // Salida de minificador. El sufijo `.min.` es la convención de la
  // herramienta (uglify/terser) y del CDN que lo sirve: el archivo servido
  // nunca es el que se edita. La forma lo confirma casi siempre por su
  // cuenta (criterio 3), pero el nombre alcanza y evita leer 64 KB.
  { suffix: ".min.js", tool: "minificador JS" },
  { suffix: ".min.mjs", tool: "minificador JS" },
  { suffix: "-min.js", tool: "minificador JS (grafía de Closure/YUI)" },
];

/* ── 2. Marcas de cabecera de código generado ─────────────────────────────
 *
 * Un generador serio ANUNCIA que el archivo es generado, en las primeras
 * líneas, porque su propio ecosistema necesita reconocerlo (para no
 * lintearlo, para colapsarlo en el diff, para no editarlo a mano). Eso hace
 * de la marca el criterio más genérico de todos: no depende del lenguaje ni
 * del repo, sólo de que quien escribió el archivo no fue una persona.
 *
 * Origen de cada marca — todas son convenciones publicadas por el ecosistema
 * que las emite, no invenciones de este proyecto:
 *   · `code generated by … do not edit.` — REGLA del proyecto Go
 *     (go.dev/s/generatedcode): la línea debe matchear
 *     `^// Code generated .* DO NOT EDIT\.$` y estar antes del `package`.
 *     La emiten protoc-gen-go, stringer, mockgen, sqlc, etc.
 *   · `@generated` — anotación de código generado de Meta, reconocida por
 *     Phabricator/Sapling y usada para colapsar el diff.
 *   · `<auto-generated` — el comentario XML que abre todo archivo generado
 *     por herramientas de Microsoft (`// <auto-generated />`).
 *   · `do not edit` suelto — la forma en inglés que emiten protoc, thrift,
 *     swagger-codegen, bindgen y compañía cuando no siguen ninguna de las
 *     anteriores.
 *
 * DOS restricciones, y las dos salieron de falsos positivos MEDIDOS, no de
 * precaución teórica:
 *
 *   1. Sólo dentro de las primeras `GENERATED_MARKER_LINES` líneas: una
 *      CABECERA. Un `DO NOT EDIT` en el medio de un archivo es una
 *      advertencia sobre un bloque, no una declaración sobre el archivo.
 *   2. La marca tiene que ARRANCAR la línea, después de un prefijo de
 *      comentario (`//`, `#`, `*`, `--`, `<!--`, `;`, `%`). Sin esto, la
 *      primera corrida de humo sobre `src/` de este mismo repo excluyó ESTE
 *      archivo: su docstring nombra `DO NOT EDIT` en el medio de una oración
 *      en prosa. Un archivo que HABLA de la convención no es un archivo
 *      generado, y la diferencia observable entre los dos casos es
 *      exactamente la posición. No es una restricción inventada para tapar
 *      ese caso: es la forma en que la propia regla de Go la especifica
 *      (`^// Code generated .* DO NOT EDIT\.$`, anclada a los dos extremos).
 *
 * RECHAZADO: `do not modify` a secas. Aparece en comentarios escritos a mano
 * ("do not modify without updating Y") incluso al principio de una línea, y
 * el requisito de seguridad manda no excluir ante la duda. `generated by` en
 * cambio SÍ entra, pero sólo anclado: una línea de cabecera que ARRANCA con
 * "Generated by …" está declarando lo que es el archivo.
 */
const GENERATED_MARKER_LINES = 40;
/**
 * Prefijo de comentario de cualquiera de los lenguajes soportados, más el `*`
 * de continuación de bloque. Deliberadamente NO incluye backtick ni `·`: eso
 * es prosa, y es lo que separa a un archivo generado de uno que documenta la
 * convención.
 */
const GENERATED_MARKER_RE =
  /^[\s/*#!;%<>-]*(?:@generated\b|<auto-generated|code generated by\b|(?:auto-?|automatically )?generated (?:by|file|code|with)\b|this (?:file|code|class) (?:is|was) (?:auto-?|automatically )?generated\b|do not edit\b|do not modify this file\b)/i;

/* ── 3. Minificado por FORMA ──────────────────────────────────────────────
 *
 * El único criterio que no puede apoyarse en ningún nombre: un bundle
 * minificado puede llamarse `app.a1b2c3.js` y no tener marca ninguna. Lo que
 * SÍ tiene, siempre, es la forma: el minificador borra los saltos de línea,
 * así que el largo medio de línea explota y aparecen líneas que ninguna
 * persona escribe.
 *
 * Dos condiciones, ambas necesarias:
 *
 *   1. `meanLineLength > MINIFIED_MEAN_LINE_LENGTH` (110). El umbral es el de
 *      GitHub Linguist (`Generated#minified_files?`, que declara minificado
 *      un `.js`/`.css` cuyo promedio de largo de línea supera 110). Se lo
 *      toma prestado en vez de inventar uno propio, y se lo aplica a todo
 *      lenguaje en vez de sólo a JS/CSS porque la propiedad es del acto de
 *      minificar, no de la extensión.
 *   2. `maxLineLength >= MINIFIED_LONG_LINE` (1000). El promedio solo no
 *      alcanza: un archivo con líneas prolijas pero largas (genéricos de
 *      Java, tablas de datos alineadas) puede pasar de 110 sin ser generado.
 *      Exigir además UNA línea de 1000 caracteres —diez veces el ancho de
 *      cualquier guía de estilo escrita— pide evidencia de empaquetado real.
 *
 * Se mide sobre el prefijo leído (`PROBE_BYTES`), descartando la última línea
 * si quedó cortada por el corte de lectura, para no contar como "línea larga"
 * un pedazo de línea. Muestrear el arranque alcanza porque la minificación es
 * uniforme sobre todo el archivo: no existe el archivo minificado sólo al
 * final.
 */
const MINIFIED_MEAN_LINE_LENGTH = 110;
const MINIFIED_LONG_LINE = 1000;

/* ── 4. Árbol de test, por nombre que la HERRAMIENTA busca o exige ────────
 *
 * D-TEST. Medido sobre el corpus de 8 lenguajes: el 51-52 % de las hipótesis
 * vivas de newtonsoft-json (C#) y el 17 % (histórico, hoy 0 %, ver sección 5)
 * de las de guava (Java) colgaban de árboles de test — el caso de cabecera es
 * `TypeNameHandlingTests.cs`, 2675 líneas, leído como si fuera una fachada de
 * producción que alguien puentea.
 *
 * Esto NO vivía acá antes de D-TEST: existía repartido en `code-analyzer.ts`
 * (`TEST_DIR_NAMES`/`TEST_FILE_PATTERNS`/`isTestPath`), sin pasar por
 * `onExcluded` — es decir, sin auditoría: `measure-ingest-exclusion.mts` no
 * podía ver ni una de estas exclusiones, y la comparación case-SENSITIVE
 * (`TEST_DIR_NAMES.has(segment)` sin normalizar) dejaba pasar cualquier
 * variante con mayúscula (`Tests`, no sólo `tests`) sin decirlo en ningún
 * lado. Se consolida acá por la misma razón que las otras cuatro categorías:
 * una exclusión que puede sacar código legítimo tiene que ser auditable.
 *
 * CRITERIO DE ADMISIÓN — el mismo que ya exige el resto del archivo: el
 * nombre lo fija la herramienta, no el proyecto. Nombre por nombre:
 *
 *   · `spec`, `test`, `tests` — layout por DEFECTO que la propia herramienta
 *     busca sin configuración: Maven/Gradle fijan `src/test/java` (test es el
 *     nombre del source set, no una elección del proyecto); RSpec busca
 *     `spec/` y Minitest `test/` sin config adicional.
 *   · `__tests__` — convención de descubrimiento de Jest (y de la config por
 *     defecto de Vitest/Jasmine cuando no se listan `include` explícitos):
 *     el doble guión bajo lo eligió la herramienta para no chocar con un
 *     directorio de proyecto llamado `tests`.
 *
 * Comparación case-INSENSITIVE a propósito (arreglo de D-TEST, no
 * comportamiento previo): un proyecto .NET en Windows puede versionar `Test/`
 * con mayúscula y el propio ecosistema trata ambos como el mismo nombre —
 * mismo argumento que ya usa `excludedByPath` para `.Designer.cs`.
 *
 * RECHAZADO: cualquier fragmento de nombre de PROYECTO tipo `Newtonsoft.Json.
 * Tests` como directorio suelto. No hay herramienta de .NET que fije esa
 * convención — a diferencia de Go (`_test.go`, el COMPILADOR excluye el
 * archivo de `go build` y sólo `go test` lo compila) o de Maven/Gradle
 * (arriba), acá el sufijo `.Tests` es una sugerencia de plantilla
 * (`dotnet new xunit`, el asistente de Visual Studio), no una regla: nada
 * impide llamar al proyecto `Newtonsoft.Json.Regression` y que sea el mismo
 * árbol de test, o llamarlo `Foo.Tests` y que sea una librería de producción
 * de utilidades de aserción (como pasa con `guava-testlib`, ver sección 5).
 * Por eso el criterio de admisión para .NET vive en la sección 5, anclado en
 * el DESCRIPTOR DE PROYECTO, no en el nombre del directorio.
 *
 * RECHAZADO, y era el comportamiento hasta esta ola: `features` a secas.
 * A diferencia de `spec`/`test`/`tests`/`__tests__` —donde el NOMBRE alcanza
 * porque ninguna herramienta seria usa ese nombre para código de producción—
 * `features` es también el nombre que un proyecto le da a un paquete propio
 * (una carpeta de módulos de frontend, un grupo de interfaces, un flag de
 * capacidades) sin que ningún runner BDD esté involucrado. Medido sobre el
 * corpus: 138 archivos fuente bajo un directorio llamado `features`
 * (gitea 100, guava 28, nest 7, jekyll 3) y sólo los 3 de jekyll son de un
 * árbol Cucumber real — los otros 135 son código de producción que el nombre
 * solo podaba en silencio. Ver `isFeaturesDirName`/`excludedGherkinFeaturesDir`
 * más abajo: el mismo caso, resuelto con el criterio estructural que le
 * faltaba en vez de con el nombre a secas.
 */
const TEST_DIR_NAMES = new Set(["spec", "test", "tests", "__tests__"]);

/** True cuando el nombre de un directorio (no la ruta completa) es uno de los de arriba. */
export function isTestDirName(name: string): boolean {
  return TEST_DIR_NAMES.has(name.toLowerCase());
}

/* ── 4b. `features`: mismo layout por defecto, pero el nombre NO alcanza ──
 *
 * D-TEST, corrección de esta ola. Un runner BDD (Cucumber, Behat y familia)
 * busca por defecto adentro de un directorio `features/` — layout por
 * defecto de la HERRAMIENTA, el mismo argumento que admite el resto de
 * `TEST_DIR_NAMES`. La diferencia es que acá el nombre solo NO distingue
 * "layout que la herramienta exige" de "nombre que un proyecto eligió para
 * un paquete propio", porque no hay compilador ni build tool que trate
 * `features/` como especial por sí solo (a diferencia de `src/test/java` de
 * Maven/Gradle, donde el NOMBRE es el contrato). Por eso el criterio de
 * admisión no es el nombre del directorio sino lo que la herramienta EXIGE
 * adentro: al menos un archivo `.feature` — el formato Gherkin, la única
 * forma de escenario que un runner BDD reconoce y la razón por la que
 * `features/` existe como convención en primer lugar.
 *
 * Se mira sólo el nivel INMEDIATO del directorio (un `readdir` extra, no un
 * recorrido) — mismo argumento de costo que `excludedDotnetTestProjectDir`:
 * clasificar archivo por archivo es lo que se quiere evitar, pero UNA
 * lectura de directorio por cada carpeta llamada `features` es barata y
 * alcanza para el caso medido (jekyll: los 27 `.feature` viven directamente
 * adentro de `features/`, no en un subdirectorio).
 *
 * Consecuencia directa del requisito de seguridad del módulo: si el
 * `readdir` falla o no hay ni un `.feature`, NO se excluye — un paquete de
 * producción llamado `features` (la interfaz `ExecutionContext` de nest, el
 * módulo de flags de guava-testlib, la carpeta de componentes de gitea) se
 * camina como cualquier otro directorio.
 */
const GHERKIN_FEATURE_EXTENSION = ".feature";

/** True cuando el nombre de un directorio (no la ruta completa) es `features`. */
export function isFeaturesDirName(name: string): boolean {
  return name.toLowerCase() === "features";
}

/**
 * Decide si UN directorio ya identificado como `features` (por nombre) es
 * además un árbol Cucumber real: tiene que tener al menos un `.feature`
 * directamente adentro. `absoluteDirPath` es el directorio candidato, no su
 * padre — a diferencia de `excludedDotnetTestProjectDir`, que reutiliza los
 * `fileNames` que el caller ya leyó, acá no hay lectura previa que reusar
 * porque la decisión es sobre un directorio que el walk todavía no visitó.
 */
export async function excludedGherkinFeaturesDir(absoluteDirPath: string): Promise<Exclusion | null> {
  let entries;
  try {
    entries = await fs.readdir(absoluteDirPath, { withFileTypes: true });
  } catch {
    return null;
  }
  const featureFile = entries.find(
    (e) => e.isFile() && e.name.toLowerCase().endsWith(GHERKIN_FEATURE_EXTENSION),
  );
  if (!featureFile) return null;
  return {
    reason: "test-tree",
    detail: `directorio "features" con Gherkin adentro (p.ej. "${featureFile.name}") — layout por defecto de un runner BDD`,
  };
}

/**
 * Sufijos/prefijos de ARCHIVO que la herramienta exige o busca por defecto
 * para descubrir el test — no una convención social del proyecto:
 *   · `_spec.rb` / `_test.rb` — RSpec / Minitest, sus propios generadores
 *     escriben exactamente ese sufijo.
 *   · `.test.<ext>` / `.spec.<ext>` — Jest/Vitest/Jasmine: es su patrón de
 *     `testMatch`/`include` por defecto.
 *   · `_test.go` — el COMPILADOR de Go, no un test runner externo: `go build`
 *     ignora estos archivos y sólo `go test` los compila. Es la más fuerte de
 *     la lista porque violarla no produce "un test mal nombrado", produce un
 *     archivo que ni siquiera compila con el binario normal.
 *   · `test_*.py` / `*_test.py` — descubrimiento por defecto de pytest y de
 *     `unittest` (`TestLoader.testMethodPrefix`/patrón `test*.py`).
 *
 * RECHAZADO: `Test.java`/`Tests.java`/`Test.cs`/`Tests.cs` sueltos. Ningún
 * compilador ni build tool de Java/.NET distingue un archivo por ese sufijo
 * —la unidad de compilación es la CLASE anotada (`@Test` de JUnit, `[Test]`/
 * `[Fact]` de NUnit/xUnit), no el nombre del archivo—, así que admitirlo acá
 * sería exactamente el léxico de dominio prohibido: una convención de
 * ecosistema sin que ninguna herramienta la fije. Medido en guava: los 10
 * archivos que sobreviven con ese sufijo (`MapInterfaceTest.java`,
 * `AbstractPackageSanityTests.java`…) son SIEMPRE código de producción de
 * `guava-testlib`, la librería de soporte de test que Guava publica en Maven
 * Central — excluirlos por el sufijo habría sido el falso positivo que este
 * módulo existe para evitar.
 */
const TEST_FILE_PATTERNS: readonly RegExp[] = [
  /_spec\.rb$/,
  /_test\.rb$/,
  /\.test\.[^.]+$/,
  /\.spec\.[^.]+$/,
  /_test\.go$/,
  /^test_[^/]*\.py$/,
  /_test\.py$/,
];

/** Exclusión de archivo por nombre de test — ver criterio de admisión arriba. */
export function excludedByTestFilePattern(relativePath: string): Exclusion | null {
  const basename = path.basename(relativePath);
  for (const pattern of TEST_FILE_PATTERNS) {
    if (pattern.test(basename)) {
      return { reason: "test-tree", detail: `nombre de archivo de test: "${basename}" matchea ${pattern}` };
    }
  }
  return null;
}

/**
 * Cuánto se lee de cada archivo para decidir. 64 KiB es UNA sola lectura y
 * cubre entero a la enorme mayoría de los archivos fuente, así que para ellos
 * la medida de forma es exacta, no muestreada.
 */
const PROBE_BYTES = 64 * 1024;

/** Exclusión decidible sólo con la ruta — sin abrir el archivo. */
export function excludedByPath(relativePath: string): Exclusion | null {
  const basename = path.basename(relativePath).toLowerCase();
  for (const { suffix, tool } of GENERATED_NAME_SUFFIXES) {
    if (basename.endsWith(suffix)) {
      return { reason: "generated-name", detail: `sufijo "${suffix}" (${tool})` };
    }
  }
  return null;
}

/**
 * Exclusión decidible mirando el arranque del archivo. `truncated` dice si
 * `text` es el archivo entero o sólo su prefijo, porque de eso depende si la
 * última línea está cortada.
 */
export function excludedByContent(text: string, truncated: boolean): Exclusion | null {
  const lines = text.split("\n");
  // Una línea cortada por el corte de lectura no es una línea: ni su largo ni
  // su contenido son observaciones válidas.
  if (truncated && lines.length > 1) lines.pop();
  if (lines.length === 0) return null;

  const head = lines.slice(0, GENERATED_MARKER_LINES);
  for (let i = 0; i < head.length; i++) {
    const match = GENERATED_MARKER_RE.exec(head[i]!);
    if (match) {
      return {
        reason: "generated-marker",
        detail: `marca de código generado en la línea ${i + 1}: ${JSON.stringify(match[0].trim().slice(0, 80))}`,
      };
    }
  }

  let total = 0;
  let longest = 0;
  for (const line of lines) {
    total += line.length;
    if (line.length > longest) longest = line.length;
  }
  const mean = total / lines.length;
  if (mean > MINIFIED_MEAN_LINE_LENGTH && longest >= MINIFIED_LONG_LINE) {
    return {
      reason: "minified-shape",
      detail:
        `largo medio de línea ${mean.toFixed(0)} (> ${MINIFIED_MEAN_LINE_LENGTH}) ` +
        `y línea más larga ${longest} (>= ${MINIFIED_LONG_LINE})`,
    };
  }
  return null;
}

/**
 * Lee el prefijo de un archivo con UNA sola apertura. Devuelve `null` si no se
 * pudo leer — un archivo ilegible no se excluye por eso; que decida el resto
 * del pipeline, que ya sabe fallar por archivo.
 */
async function probe(absolutePath: string): Promise<{ text: string; truncated: boolean } | null> {
  let handle;
  try {
    handle = await fs.open(absolutePath, "r");
  } catch {
    return null;
  }
  try {
    const buffer = Buffer.allocUnsafe(PROBE_BYTES);
    const { bytesRead } = await handle.read(buffer, 0, PROBE_BYTES, 0);
    return {
      text: buffer.subarray(0, bytesRead).toString("utf8"),
      truncated: bytesRead === PROBE_BYTES,
    };
  } catch {
    return null;
  } finally {
    await handle.close().catch(() => {});
  }
}

/* ── 5. Proyecto .NET que el propio SDK trata como test ───────────────────
 *
 * D-TEST. El hueco medido: newtonsoft-json tiene el 52 % de sus hipótesis
 * vivas colgando de `Src/Newtonsoft.Json.Tests/` — un único árbol, ninguna
 * convención de NOMBRE de directorio lo cubre (ver el RECHAZADO de la
 * sección 4) porque .NET no fija ningún nombre de carpeta para tests.
 *
 * Lo que SÍ fija la herramienta: `dotnet test`/VSTest sólo ejecuta un
 * proyecto si su descriptor (`.csproj`/`.fsproj`/`.vbproj` — el archivo que
 * MSBuild carga para que el proyecto EXISTA como unidad de build) referencia
 * el paquete `Microsoft.NET.Test.Sdk`. Sin esa referencia, `dotnet test`
 * devuelve cero tests encontrados sin importar cuántos `[Fact]`/`[Test]`/
 * `[TestMethod]` tenga el código — es el equivalente .NET del `_test.go` de
 * Go: no es "cómo se nombra la convención", es el mecanismo que hace que la
 * herramienta trate el árbol como test, sea NUnit, xUnit o MSTest el
 * framework de aserciones usado por encima (deliberadamente no se nombra
 * ninguno de esos tres en el criterio: el ancla es el contrato del SDK, no la
 * marca del framework).
 *
 * Verificado en el corpus (`Src/Newtonsoft.Json.Tests/Newtonsoft.Json.Tests.
 * csproj` referencia `Microsoft.NET.Test.Sdk` cuatro veces, una por grupo de
 * target framework) y el control negativo junto: `Newtonsoft.Json.
 * FuzzTests.csproj` y `Newtonsoft.Json.TestConsole.csproj` — los dos con
 * "Test(s)" en el NOMBRE del proyecto — NO referencian el SDK de test y por
 * lo tanto NO se excluyen: uno es un harness de fuzzing standalone, el otro
 * una consola manual; ninguno es lo que `dotnet test` ejecuta, y el requisito
 * de seguridad del módulo (ante la duda, no se excluye) los deja pasar tal
 * como corresponde.
 *
 * Directorio, no archivo: como `dependency-tree`, la exclusión es del árbol
 * completo bajo el descriptor — no tiene sentido clasificar archivo por
 * archivo dentro de un proyecto que el SDK entero trata como test.
 */
const NET_PROJECT_EXTENSIONS = new Set([".csproj", ".fsproj", ".vbproj"]);
const NET_TEST_SDK_MARKER = /Microsoft\.NET\.Test\.Sdk/i;

/**
 * Busca un descriptor de proyecto .NET entre `fileNames` (los archivos de UN
 * directorio, ya leídos por el caller — no vuelve a listar) y, si lo
 * encuentra, lee su contenido para decidir si el SDK de test está referenciado.
 * `null` si no hay descriptor o no se pudo leer — no tocar el resto del árbol
 * por un archivo de proyecto ilegible.
 */
export async function excludedDotnetTestProjectDir(
  absoluteDirPath: string,
  fileNames: readonly string[],
): Promise<Exclusion | null> {
  const descriptor = fileNames.find((name) => NET_PROJECT_EXTENSIONS.has(path.extname(name).toLowerCase()));
  if (!descriptor) return null;
  const probed = await probe(path.join(absoluteDirPath, descriptor));
  if (!probed) return null;
  if (NET_TEST_SDK_MARKER.test(probed.text)) {
    return {
      reason: "test-tree",
      detail: `"${descriptor}" referencia Microsoft.NET.Test.Sdk — el proyecto sólo existe para que \`dotnet test\` lo ejecute`,
    };
  }
  return null;
}

/* ── 6. Procedencia declarada AJENA — la copia de upstream sin carpeta ────
 *
 * N10 dejó el criterio implementado, testeado y medido en
 * `detect/primitivas/n10-no-es-producto.ts` (`firmaDeProcedencia` /
 * `procedenciaDominante` / `esProcedenciaAjena`); acá está el I/O que lo
 * cablea, que es lo único que faltaba. El criterio, en una línea: **un archivo
 * cuya cabecera atribuye la autoría a alguien que no es a quien se la atribuye
 * la abrumadora mayoría de los archivos del mismo repo es una copia traída de
 * afuera.** No hay ni un nombre propio en el código: los dos lados de la
 * comparación los aportan los archivos analizados, así que funciona igual en un
 * repo de una empresa que nunca vimos, y se abstiene por completo en un repo
 * que no usa cabeceras (medido: se abstiene en 9 de los 13 del corpus).
 *
 * POR QUÉ NO ES UN CRITERIO POR ARCHIVO, aunque decida por archivo — y por qué
 * eso obliga a la forma de dos fases que tiene {@link classifyFile}. Los otros
 * cinco criterios se contestan mirando UN archivo: el nombre lo fija un
 * generador, la cabecera lo declara generado, la forma es de minificador. Éste
 * no: "ajeno" es una comparación contra un ESTADÍSTICO del repo (la firma
 * dominante), que no existe hasta que se vieron todos los archivos. Así que la
 * ingesta lo resuelve en dos tiempos, y no cuesta ni una lectura de más:
 *
 *   1. mientras camina, {@link classifyFile} devuelve —además de la exclusión
 *      de siempre— la FIRMA de la cabecera, sacada del MISMO texto que ya se
 *      leyó para las categorías 1-3 (`probe`, una sola apertura por archivo);
 *   2. terminado el recorrido, quien llama pide {@link dominantProvenance} de
 *      todas las firmas y descarta con {@link excludedByProvenance} los
 *      archivos cuya firma no es la del repo.
 *
 * LA POBLACIÓN de la fase 2 es exactamente la de los archivos que iban a
 * analizarse — ni más ni menos — y eso NO es un detalle de implementación: la
 * compuerta de cobertura de `procedenciaDominante` (fracción de archivos con
 * firma) es una fracción, y su denominador define qué quiere decir "la
 * convención de este repo". Contar archivos que el análisis nunca va a mirar
 * (un `node_modules` versionado, un árbol de test podado, un `.md`) mueve esa
 * fracción sin decir nada sobre el código analizado. Por eso el estadístico se
 * arma con las firmas que la propia ingesta juntó al pasar, y no con un segundo
 * recorrido del disco que tendría que re-declarar —y mantener sincronizadas—
 * las mismas podas.
 *
 * REQUISITO DE SEGURIDAD, el del módulo entero: las tres compuertas de
 * `procedenciaDominante` (muestra mínima, cobertura, mayoría) fallan siempre
 * hacia NO EXCLUIR, y un archivo sin firma nunca es ajeno. Un repo sin
 * convención de cabecera no pierde ni un archivo.
 */

/** El veredicto completo de mirar un archivo candidato UNA vez. */
export interface FileClassification {
  /** Por qué NO entra al análisis, o `null` si entra. */
  exclusion: Exclusion | null;
  /**
   * La firma de procedencia de su cabecera, o `null` si no declara ninguna —
   * el caso mayoritario. Es la entrada de la fase 2 (sección 6). Vale `null`
   * también cuando el archivo ya quedó excluido: un archivo que no entra al
   * análisis tampoco vota qué es la convención del repo.
   */
  provenance: string | null;
}

/**
 * La firma que declara la abrumadora mayoría de los archivos del repo, o
 * `null` cuando no hay tal cosa y entonces no se excluye nada. `signatures`
 * es UNA entrada por archivo que entró al análisis, con `null` para los que no
 * declaran atribución: los `null` cuentan para la cobertura, que es
 * justamente lo que la compuerta mide. Ver la sección 6 sobre la población.
 */
export function dominantProvenance(signatures: Iterable<string | null>): string | null {
  return procedenciaDominante(signatures);
}

/**
 * La fase 2 para UN archivo: su firma contra la del repo. `null` en los tres
 * casos seguros (el archivo no declara nada, el repo no tiene procedencia
 * dominante, o las dos atribuciones son la misma escrita distinto).
 */
export function excludedByProvenance(
  signature: string | null,
  dominant: string | null,
): Exclusion | null {
  const ajena = esProcedenciaAjena(signature, dominant);
  return ajena === null ? null : { reason: "vendored-provenance", detail: ajena.detalle };
}

/**
 * La pregunta completa para un archivo candidato: ¿entra al análisis? y, si
 * entra, ¿a quién le atribuye la autoría su cabecera? Barato primero: la
 * prueba de nombre no toca el disco, y sólo se lee el archivo si la pasa —
 * y esa ÚNICA lectura sirve para las dos preguntas.
 */
export async function classifyFile(
  absolutePath: string,
  relativePath: string,
): Promise<FileClassification> {
  const byPath = excludedByPath(relativePath);
  if (byPath) return { exclusion: byPath, provenance: null };
  const byTestFile = excludedByTestFilePattern(relativePath);
  if (byTestFile) return { exclusion: byTestFile, provenance: null };
  const probed = await probe(absolutePath);
  // Un archivo ilegible no se excluye por serlo (que decida el resto del
  // pipeline), y tampoco vota: no se leyó nada suyo.
  if (!probed) return { exclusion: null, provenance: null };
  const byContent = excludedByContent(probed.text, probed.truncated);
  if (byContent) return { exclusion: byContent, provenance: null };
  return { exclusion: null, provenance: firmaDeProcedencia(probed.text) };
}

/**
 * Sólo la mitad "¿entra?" de {@link classifyFile}, para quien no participa de
 * la fase 2 (la procedencia ajena NO se decide acá — ver la sección 6).
 */
export async function classifyExclusion(
  absolutePath: string,
  relativePath: string,
): Promise<Exclusion | null> {
  return (await classifyFile(absolutePath, relativePath)).exclusion;
}
